name: found_it_frontend
description: "A lost and found application to help people recover their belongings."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  path_provider: ^2.0.0
  path_provider_android: ^2.0.0
  image_picker: ^1.0.4
  provider: ^6.0.5
  universal_platform: ^1.0.0+1
  shared_preferences: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  web_socket_channel: ^2.4.0
  stomp_dart_client: ^0.4.4
  jwt_decoder: ^2.0.1
  share_plus: ^10.1.1
  dotted_border: ^2.0.0
  url_launcher: ^6.2.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"  # Icon name for Android
  ios: true                 # Creates iOS icons
  image_path: "assets/icon/icon.png"  # Path to your icon image
  adaptive_icon_foreground: null  # Disable adaptive icons
  adaptive_icon_background: null